#!/bin/bash

# Multi-Language AI Web Agent (Bash Version)
# Uses curl to generate projects directly without Python/Xcode.

if [ -z "$1" ]; then
  echo "Usage: ./agent.sh '<prompt_describing_project>'"
  exit 1
fi

PROMPT="$1"
OUTPUT_DIR="output_sh"

echo "Generating project for prompt: '$PROMPT'..."
mkdir -p "$OUTPUT_DIR"

# Check if a valid API key is present
if [[ -z "$GEMINI_API_KEY" || "$GEMINI_API_KEY" == "REPLACE_WITH_VALID_KEY" || "$GEMINI_API_KEY" == "YOUR_REAL_API_KEY" ]]; then
  echo "⚠️ No valid GEMINI_API_KEY detected! Using MOCK MODE to simulate the agent..."
  
  RESPONSE=$(cat <<EOF
{
  "candidates": [
    {
      "content": {
        "parts": [
          {
            "text": "==== FILE: mock_app.js ====\nconsole.log('Mock JS File generated by Bash Agent');\n====================================\n\n==== FILE: mock_index.html ====\n<h1>Mock Bash Agent Website</h1>\n===================================="
          }
        ]
      }
    }
  ]
}
EOF
)
  
  echo "$RESPONSE" > "$OUTPUT_DIR/raw_api_response.json"
  echo "Project generation complete! Saved raw mock response to $OUTPUT_DIR/raw_api_response.json"
  exit 0
fi

JSON_PAYLOAD=$(cat <<EOF
{
  "contents": [{
    "parts": [{"text": "$PROMPT"}]
  }],
  "systemInstruction": {
    "parts": [{"text": "You are an expert multi-language software developer. You generate complete projects containing multiple files. You must output the code for each file using the following format exactly:\n\n==== FILE: path/to/filename.ext ====\n<file contents here>\n====================================\n\nDo NOT use markdown code blocks around the content. Just provide the raw content between the boundary markers. Ensure that you generate ALL necessary files."}]
  },
  "generationConfig": {
    "temperature": 0.7
  }
}
EOF
)

# Use curl to hit the Gemini API directly
RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_API_KEY}" \
  -H 'Content-Type: application/json' \
  -d "$JSON_PAYLOAD")

# Check for API errors
ERROR=$(echo "$RESPONSE" | grep -o '"error":')
if [ ! -z "$ERROR" ]; then
  echo "API Error occurred. Check your API key."
  echo "$RESPONSE"
  exit 1
fi

echo "$RESPONSE" > "$OUTPUT_DIR/raw_api_response.json"
echo "Project generation complete!"
echo "Because standard macOS Bash lacks JSON parsers, the raw API response containing your code files has been saved to: $OUTPUT_DIR/raw_api_response.json"
